[package]
name = "rust_api_example"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
dashmap = "6.1.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }

[dev-dependencies]
serde_json = "1.0.149"
tower = { version = "0.5.3", features = ["util"] }
